version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: scheduler-database
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    sysctls:
      net.core.somaxconn: 1024
      kernel.shmmax: 33554432
      kernel.shmall: 2097152

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
      - postgres
    environment:
      DATABASE_URL: postgres://docker:docker@postgres-db:5432/docker 

volumes:
  grafana-data:
  postgres_data:
