version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    sysctls:
      - net.core.somaxconn=1024
      - kernel.shmmax=33554432
      - kernel.shmall=2097152

volumes:
  postgres_data:
    driver: local