basePath: /api/v1
info:
  contact:
    email: hebertsantosdeveloper@gmail.com
    name: Hebert santos
    url: https://www.hebertzin.com/
  description: Saas plataform
  title: Scheduler app
  version: "1.0"
paths: {}
swagger: "2.0"
