basePath: /api/v1
definitions:
  domains.HttpResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  domains.User:
    properties:
      email:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      name:
        type: string
      password:
        type: string
    type: object
  dto.UserDTO:
    properties:
      age:
        type: integer
      city:
        type: string
      email:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: hebertsantosdeveloper@gmail.com
    name: Hebert Santos
    url: https://www.hebertzin.com/
  description: Saas plataforma
  title: Scheduler app
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all users in the system
      produces:
      - application/json
      responses:
        "200":
          description: Users retrieved successfully
          schema:
            allOf:
            - $ref: '#/definitions/domains.HttpResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dto.UserDTO'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domains.HttpResponse'
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create a new user with the provided data
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domains.User'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            allOf:
            - $ref: '#/definitions/domains.HttpResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserDTO'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domains.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domains.HttpResponse'
      summary: Add a new user
      tags:
      - Users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a user by their unique ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User found successfully
          schema:
            allOf:
            - $ref: '#/definitions/domains.HttpResponse'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserDTO'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domains.HttpResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/domains.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domains.HttpResponse'
      summary: Find a user by ID
      tags:
      - Users
swagger: "2.0"
