name: Deploy

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/scheduler:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/scheduler:${{ github.sha }}

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/scheduler:latest
